### ISSUE TITLE
Build failure - Failed to find License for 3 artifacts

### ISSUE THREAD

**Issue by thanhnk1602** [52North/sos-ses-feeder#2]
i clone this, from develop branch, I add two jar file `oxf-sos-adapter-2.0.0-alpha.3.2-SNAPSHOT.jar` and `oxf-ses-adapter-2.0.0-alpha.3.2-SNAPSHOT.jar` then run command:

`mvn clean license:format notice:generate install `

and still can't build this project, error show like below:

`Failed to find Licenses for the following dependencies:
[ERROR] 	org.n52.sensorweb:oxf-ses-adapter:jar:2.0.0-alpha.3.2-SNAPSHOT:compile
[ERROR] 	org.n52.sensorweb:oxf-sos-adapter:jar:2.0.0-alpha.3.2-SNAPSHOT:compile
[ERROR] 	org.slf4j:slf4j-api:jar:1.5.8:compile
[ERROR] Try adding them to a 'licenseMapping' file.
[ERROR] A stub license-mapping.xml file containing the unresolved dependencies has been written to: /home/iot/workspace/sos-ses-feeder/target/license-mappings.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.810 s
[INFO] Finished at: 2017-03-20T01:13:05+07:00
[INFO] Final Memory: 12M/192M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jasig.maven:maven-notice-plugin:1.0.6:generate (default-cli) on project 52n-sos-ses-feeder: Failed to find Licenses for 3 artifacts -> [Help 1]`

**Comment by ridoo** [comment]
should be fixed on `develop` (e3bf8fc63203dba2975ea7d84d3c732cf74835cd)

**Comment by thanhnk1602** [comment]
it works.
